### ISSUE TITLE
data-dir doesn't exist

### ISSUE THREAD

**Issue by vterdunov** [fcole90/fah-snap#5]
Thanks for the package. It looks like a minor issue.
Version: `folding-at-home-fcole90  7.5.1`
Revision: `16`

`ls -la ~/snap/folding-at-home-fcole90/current/`
```bash
<skipped>
lrwxrwxrwx 1 slick slick   48 мар 27 20:27 .themes -> /snap/folding-at-home-fcole90/16/data-dir/themes
```

`ls /snap/folding-at-home-fcole90/16/`
```bash
bin  etc  flavor-select  lib  meta  snap  usr  var
```
There is no `data-dir`.

**Comment by fcole90** [comment]
Hi and thanks for reporting this :+1:
I can reproduce the same on my machine. Actually I don't know what is generating this symlink. I checked the deb package of FAHControl (from which we make the snap) and I couldn't find any snap folder in it (while the repo has one)..

**Comment by fcole90** [comment]
I think data-dir to exist because of the connection to the gtk themes and icons

```yaml
plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
```
